version: '3'
services:
  db:
    image: mariadb
    networks:
      - voice-web
    environment:
      - MYSQL_DATABASE=voiceweb
      - MYSQL_USER=voicecommons
      - MYSQL_PASSWORD=voicecommons
      - MYSQL_ROOT_PASSWORD=voicewebroot
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/code
    environment:
      - SERVER_CONFIG_PATH=/code/docker/local-docker-config.json
    networks:
      - voice-web
    ports:
      - 9000:9000
      - 9229:9229
    command: bash -c "/code/docker/prepare_s3.sh && yarn && yarn start"
  # database manager
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - voice-web
    container_name: adminer
networks:
  voice-web:
